import json, os, re, subprocess, threading, time, urllib.request
from pathlib import Path
from http.server import BaseHTTPRequestHandler, HTTPServer

STATE = Path('/state/cameras.json'); CONFIG = Path('/frigate/config.yml')
SCAN = int(os.getenv('SCAN_SECONDS','30')); LOCK = threading.Lock()

def usb_devices():
    out=[]
    nodes=[]
    try:
        listing=subprocess.check_output(['v4l2-ctl','--list-devices'],text=True,timeout=5)
        groups=[]
        for line in listing.splitlines():
            if line and not line[0].isspace(): groups.append([])
            elif '/dev/video' in line and groups: groups[-1].append(line.strip())
        nodes=[g[0] for g in groups if g]
    except Exception: nodes=[str(p) for p in sorted(Path('/dev').glob('video*'))]
    for node in nodes:
        p=Path(node)
        try:
            info=subprocess.check_output(['v4l2-ctl','--device',str(p),'--all'],stderr=subprocess.DEVNULL,text=True,timeout=3)
            if 'Driver name' in info:
                modes=subprocess.check_output(['v4l2-ctl','--device',str(p),'--list-formats-ext'],stderr=subprocess.DEVNULL,text=True,timeout=3)
                sizes=[(int(w),int(h)) for w,h in re.findall(r'(\d+)x(\d+)',modes)]
                width,height=max(sizes,key=lambda x:x[0]*x[1]) if sizes else (640,480)
                fps=[float(x) for x in re.findall(r'\((\d+(?:\.\d+)?) fps\)',modes)]
                rate=max(fps) if fps else 5
                out.append({'id':p.name,'kind':'usb','path':str(p),'name':p.name,'enabled':True,'status':'available','width':width,'height':height,'fps':rate})
        except Exception: pass
    return out

def load():
    try: return json.loads(STATE.read_text())
    except Exception: return {}

def save(c):
    STATE.parent.mkdir(parents=True,exist_ok=True); STATE.write_text(json.dumps(c,indent=2)); STATE.chmod(0o600)

def render(cams):
    lines=['# Generated by CasaGuard camera-manager. Edit cameras through the manager API.','go2rtc:','  streams:']
    for cam in cams.values():
        if cam.get('enabled',True) and cam.get('kind')=='usb':
            name=cam['name'].replace('-','_').replace(' ','_')
            lines += [f'    {name}:',f'      - "ffmpeg:device?video={cam["path"]}&video_size={cam.get("width",640)}x{cam.get("height",480)}&framerate={cam.get("fps",5)}#video=mjpeg"']
    lines += ['cameras:']
    for cam in cams.values():
        if not cam.get('enabled',True): continue
        name=cam['name'].replace('-','_').replace(' ','_')
        path=cam['path']
        if cam['kind']=='usb': source=f'rtsp://127.0.0.1:8554/{name}'
        else: stream=None; source=path
        lines += [f'  {name}:','    enabled: true','    ffmpeg:','      inputs:',f'        - path: {source}','          input_args: preset-rtsp-restream','          roles: [detect, record]','    detect:',f'      width: {cam.get("width",640)}',f'      height: {cam.get("height",480)}',f'      fps: {cam.get("fps",5)}','    record:','      enabled: true','    snapshots:','      enabled: true']
    return '\n'.join(lines)+'\n'

def scan():
    cams=load(); found=usb_devices()
    valid={d['path'] for d in found}
    for k,v in list(cams.items()):
        if v.get('kind')=='usb' and v.get('path') not in valid: cams.pop(k,None)
    for d in found: cams.setdefault(d['id'],d).update(d)
    for k,v in list(cams.items()):
        if v.get('kind')=='usb' and not Path(v['path']).exists(): v['status']='offline'
    save(cams)
    # Preserve the non-camera sections of the existing config and replace its cameras block.
    old=CONFIG.read_text() if CONFIG.exists() else ''
    head=old
    if '\ngo2rtc:' in head: head=head.split('\ngo2rtc:',1)[0]
    if '\ncameras:' in head: head=head.split('\ncameras:',1)[0]
    CONFIG.write_text(head.rstrip()+'\n\n'+render(cams))
    try:
        req=urllib.request.Request(os.getenv('FRIGATE_URL','http://frigate:5000')+'/api/config/save',method='POST',data=b'{}')
        urllib.request.urlopen(req,timeout=3).read()
    except Exception: pass

class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path=='/api/cameras':
            b=json.dumps(load()).encode(); self.send_response(200); self.send_header('Content-Type','application/json'); self.send_header('Content-Length',str(len(b))); self.end_headers(); self.wfile.write(b)
        else: self.send_error(404)
    def do_POST(self):
        if self.path=='/api/rescan': scan(); self.send_response(202); self.end_headers()
        elif self.path=='/api/cameras':
            n=int(self.headers.get('Content-Length','0')); data=json.loads(self.rfile.read(n) or b'{}')
            if not data.get('path'): self.send_error(400,'path is required'); return
            cams=load(); cid=data.get('id') or ('network-'+str(abs(hash(data['path'])))); cams[cid]={'id':cid,'kind':'network','path':data['path'],'name':data.get('name',cid),'enabled':True,'status':'configured','width':int(data.get('width',1920)),'height':int(data.get('height',1080)),'fps':float(data.get('fps',30))}; save(cams); scan(); self.send_response(201); self.end_headers()
        else: self.send_error(404)
    def log_message(self,*a): pass

def loop():
    while True:
        try: scan()
        except Exception: pass
        time.sleep(SCAN)

scan(); threading.Thread(target=loop,daemon=True).start(); HTTPServer(('0.0.0.0',8971),Handler).serve_forever()
